// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuf/mllm.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MllmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MllmRequest) Reset() {
	*x = MllmRequest{}
	mi := &file_protobuf_mllm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MllmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MllmRequest) ProtoMessage() {}

func (x *MllmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mllm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MllmRequest.ProtoReflect.Descriptor instead.
func (*MllmRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_mllm_proto_rawDescGZIP(), []int{0}
}

func (x *MllmRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MllmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsDone        bool                   `protobuf:"varint,2,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MllmResponse) Reset() {
	*x = MllmResponse{}
	mi := &file_protobuf_mllm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MllmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MllmResponse) ProtoMessage() {}

func (x *MllmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_mllm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MllmResponse.ProtoReflect.Descriptor instead.
func (*MllmResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_mllm_proto_rawDescGZIP(), []int{1}
}

func (x *MllmResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MllmResponse) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

var File_protobuf_mllm_proto protoreflect.FileDescriptor

const file_protobuf_mllm_proto_rawDesc = "" +
	"\n" +
	"\x13protobuf/mllm.proto\x12\aservice\"!\n" +
	"\vMllmRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\";\n" +
	"\fMllmResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\ais_done\x18\x02 \x01(\bR\x06isDone2F\n" +
	"\vMllmService\x127\n" +
	"\x04Chat\x12\x14.service.MllmRequest\x1a\x15.service.MllmResponse\"\x000\x01B:Z8github.com/govision-hackvidia/hackvidia-backend/protobufb\x06proto3"

var (
	file_protobuf_mllm_proto_rawDescOnce sync.Once
	file_protobuf_mllm_proto_rawDescData []byte
)

func file_protobuf_mllm_proto_rawDescGZIP() []byte {
	file_protobuf_mllm_proto_rawDescOnce.Do(func() {
		file_protobuf_mllm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_mllm_proto_rawDesc), len(file_protobuf_mllm_proto_rawDesc)))
	})
	return file_protobuf_mllm_proto_rawDescData
}

var file_protobuf_mllm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_mllm_proto_goTypes = []any{
	(*MllmRequest)(nil),  // 0: service.MllmRequest
	(*MllmResponse)(nil), // 1: service.MllmResponse
}
var file_protobuf_mllm_proto_depIdxs = []int32{
	0, // 0: service.MllmService.Chat:input_type -> service.MllmRequest
	1, // 1: service.MllmService.Chat:output_type -> service.MllmResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_mllm_proto_init() }
func file_protobuf_mllm_proto_init() {
	if File_protobuf_mllm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_mllm_proto_rawDesc), len(file_protobuf_mllm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_mllm_proto_goTypes,
		DependencyIndexes: file_protobuf_mllm_proto_depIdxs,
		MessageInfos:      file_protobuf_mllm_proto_msgTypes,
	}.Build()
	File_protobuf_mllm_proto = out.File
	file_protobuf_mllm_proto_goTypes = nil
	file_protobuf_mllm_proto_depIdxs = nil
}
