# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hazalert.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hazalert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehazalert.proto\x12\x07service\" \n\x0fHazalertRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\",\n\x10HazalertResponse\x12\x18\n\x10nearest_distance\x18\x01 \x01(\x02\x32O\n\x0bMllmService\x12@\n\x07Predict\x12\x18.service.HazalertRequest\x1a\x19.service.HazalertResponse\"\x00\x42:Z8github.com/govision-hackvidia/hackvidia-backend/protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hazalert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/govision-hackvidia/hackvidia-backend/protobuf'
  _globals['_HAZALERTREQUEST']._serialized_start=27
  _globals['_HAZALERTREQUEST']._serialized_end=59
  _globals['_HAZALERTRESPONSE']._serialized_start=61
  _globals['_HAZALERTRESPONSE']._serialized_end=105
  _globals['_MLLMSERVICE']._serialized_start=107
  _globals['_MLLMSERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
