// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: hazalert.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HazalertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HazalertRequest) Reset() {
	*x = HazalertRequest{}
	mi := &file_hazalert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HazalertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HazalertRequest) ProtoMessage() {}

func (x *HazalertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hazalert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HazalertRequest.ProtoReflect.Descriptor instead.
func (*HazalertRequest) Descriptor() ([]byte, []int) {
	return file_hazalert_proto_rawDescGZIP(), []int{0}
}

func (x *HazalertRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type HazalertResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NearestDistance float32                `protobuf:"fixed32,1,opt,name=nearest_distance,json=nearestDistance,proto3" json:"nearest_distance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HazalertResponse) Reset() {
	*x = HazalertResponse{}
	mi := &file_hazalert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HazalertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HazalertResponse) ProtoMessage() {}

func (x *HazalertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hazalert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HazalertResponse.ProtoReflect.Descriptor instead.
func (*HazalertResponse) Descriptor() ([]byte, []int) {
	return file_hazalert_proto_rawDescGZIP(), []int{1}
}

func (x *HazalertResponse) GetNearestDistance() float32 {
	if x != nil {
		return x.NearestDistance
	}
	return 0
}

var File_hazalert_proto protoreflect.FileDescriptor

const file_hazalert_proto_rawDesc = "" +
	"\n" +
	"\x0ehazalert.proto\x12\aservice\"'\n" +
	"\x0fHazalertRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"=\n" +
	"\x10HazalertResponse\x12)\n" +
	"\x10nearest_distance\x18\x01 \x01(\x02R\x0fnearestDistance2S\n" +
	"\x0fHazalertService\x12@\n" +
	"\aPredict\x12\x18.service.HazalertRequest\x1a\x19.service.HazalertResponse\"\x00B:Z8github.com/govision-hackvidia/hackvidia-backend/protobufb\x06proto3"

var (
	file_hazalert_proto_rawDescOnce sync.Once
	file_hazalert_proto_rawDescData []byte
)

func file_hazalert_proto_rawDescGZIP() []byte {
	file_hazalert_proto_rawDescOnce.Do(func() {
		file_hazalert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hazalert_proto_rawDesc), len(file_hazalert_proto_rawDesc)))
	})
	return file_hazalert_proto_rawDescData
}

var file_hazalert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hazalert_proto_goTypes = []any{
	(*HazalertRequest)(nil),  // 0: service.HazalertRequest
	(*HazalertResponse)(nil), // 1: service.HazalertResponse
}
var file_hazalert_proto_depIdxs = []int32{
	0, // 0: service.HazalertService.Predict:input_type -> service.HazalertRequest
	1, // 1: service.HazalertService.Predict:output_type -> service.HazalertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hazalert_proto_init() }
func file_hazalert_proto_init() {
	if File_hazalert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hazalert_proto_rawDesc), len(file_hazalert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hazalert_proto_goTypes,
		DependencyIndexes: file_hazalert_proto_depIdxs,
		MessageInfos:      file_hazalert_proto_msgTypes,
	}.Build()
	File_hazalert_proto = out.File
	file_hazalert_proto_goTypes = nil
	file_hazalert_proto_depIdxs = nil
}
