// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: hazalert.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HazalertService_Predict_FullMethodName = "/service.HazalertService/Predict"
)

// HazalertServiceClient is the client API for HazalertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HazalertServiceClient interface {
	Predict(ctx context.Context, in *HazalertRequest, opts ...grpc.CallOption) (*HazalertResponse, error)
}

type hazalertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHazalertServiceClient(cc grpc.ClientConnInterface) HazalertServiceClient {
	return &hazalertServiceClient{cc}
}

func (c *hazalertServiceClient) Predict(ctx context.Context, in *HazalertRequest, opts ...grpc.CallOption) (*HazalertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HazalertResponse)
	err := c.cc.Invoke(ctx, HazalertService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HazalertServiceServer is the server API for HazalertService service.
// All implementations must embed UnimplementedHazalertServiceServer
// for forward compatibility.
type HazalertServiceServer interface {
	Predict(context.Context, *HazalertRequest) (*HazalertResponse, error)
	mustEmbedUnimplementedHazalertServiceServer()
}

// UnimplementedHazalertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHazalertServiceServer struct{}

func (UnimplementedHazalertServiceServer) Predict(context.Context, *HazalertRequest) (*HazalertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedHazalertServiceServer) mustEmbedUnimplementedHazalertServiceServer() {}
func (UnimplementedHazalertServiceServer) testEmbeddedByValue()                         {}

// UnsafeHazalertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HazalertServiceServer will
// result in compilation errors.
type UnsafeHazalertServiceServer interface {
	mustEmbedUnimplementedHazalertServiceServer()
}

func RegisterHazalertServiceServer(s grpc.ServiceRegistrar, srv HazalertServiceServer) {
	// If the following call pancis, it indicates UnimplementedHazalertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HazalertService_ServiceDesc, srv)
}

func _HazalertService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HazalertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HazalertServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HazalertService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HazalertServiceServer).Predict(ctx, req.(*HazalertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HazalertService_ServiceDesc is the grpc.ServiceDesc for HazalertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HazalertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.HazalertService",
	HandlerType: (*HazalertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _HazalertService_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hazalert.proto",
}
