// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: mllm.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MllmService_Chat_FullMethodName = "/service.MllmService/Chat"
)

// MllmServiceClient is the client API for MllmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MllmServiceClient interface {
	Chat(ctx context.Context, in *MllmRequest, opts ...grpc.CallOption) (*MllmResponse, error)
}

type mllmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMllmServiceClient(cc grpc.ClientConnInterface) MllmServiceClient {
	return &mllmServiceClient{cc}
}

func (c *mllmServiceClient) Chat(ctx context.Context, in *MllmRequest, opts ...grpc.CallOption) (*MllmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MllmResponse)
	err := c.cc.Invoke(ctx, MllmService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MllmServiceServer is the server API for MllmService service.
// All implementations must embed UnimplementedMllmServiceServer
// for forward compatibility.
type MllmServiceServer interface {
	Chat(context.Context, *MllmRequest) (*MllmResponse, error)
	mustEmbedUnimplementedMllmServiceServer()
}

// UnimplementedMllmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMllmServiceServer struct{}

func (UnimplementedMllmServiceServer) Chat(context.Context, *MllmRequest) (*MllmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedMllmServiceServer) mustEmbedUnimplementedMllmServiceServer() {}
func (UnimplementedMllmServiceServer) testEmbeddedByValue()                     {}

// UnsafeMllmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MllmServiceServer will
// result in compilation errors.
type UnsafeMllmServiceServer interface {
	mustEmbedUnimplementedMllmServiceServer()
}

func RegisterMllmServiceServer(s grpc.ServiceRegistrar, srv MllmServiceServer) {
	// If the following call pancis, it indicates UnimplementedMllmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MllmService_ServiceDesc, srv)
}

func _MllmService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MllmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MllmServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MllmService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MllmServiceServer).Chat(ctx, req.(*MllmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MllmService_ServiceDesc is the grpc.ServiceDesc for MllmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MllmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.MllmService",
	HandlerType: (*MllmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _MllmService_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mllm.proto",
}
