services:
  main_service:
    container_name: govision_main
    image: govision_main_service:v1.0
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8080
      - MLLM_HOST=host.docker.internal
      - MLLM_PORT=50051
      - HAZALERT_HOST=host.docker.internal
      - HAZALERT_PORT=50052
    ports:
      - "8081:8080"
    networks:
      - caddy_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  caddy_network:
    external: true
  default:
    external: true
