# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mllm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mllm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmllm.proto\x12\x07service\"9\n\x0bMllmRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\x05image\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_image\"\x1c\n\x0cMllmResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2D\n\x0bMllmService\x12\x35\n\x04\x43hat\x12\x14.service.MllmRequest\x1a\x15.service.MllmResponse\"\x00\x42:Z8github.com/govision-hackvidia/hackvidia-backend/protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mllm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/govision-hackvidia/hackvidia-backend/protobuf'
  _globals['_MLLMREQUEST']._serialized_start=23
  _globals['_MLLMREQUEST']._serialized_end=80
  _globals['_MLLMRESPONSE']._serialized_start=82
  _globals['_MLLMRESPONSE']._serialized_end=110
  _globals['_MLLMSERVICE']._serialized_start=112
  _globals['_MLLMSERVICE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
